---
- name: Checkout site data
  git:
    clone: yes
    dest: "/var/www/html/{{ site_hostname }}"
    repo: "{{ origin_remote }}"
  notify:
    - Restart Nginx

- name: Copy nginx config
  template:
    src: nginx.conf
    dest: "/etc/nginx/conf.d/{{ site_hostname }}.conf"
  notify:
    - Restart Nginx
